name: MicroG Update

permissions:
  contents: read

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 */3 * *"

jobs:
  check-update:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Download latest MicroG APK
        run: |
          gh release download \
            --repo MorpheApp/MicroG-RE \
            --pattern "*.apk"

      - name: Rename APK
        run: |
          file=$(ls *.apk | head -n 1)
          mv "$file" 1microg.apk

      - name: Upload artifact
        uses: actions/upload-artifact@main
        with:
          name: microg
          path: 1microg.apk
