name: MicroG Update
permissions: write-all
on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 */3 * *"

jobs:
  check-update:
    runs-on: ubuntu-latest
    env:
      repository: ${{ github.repository }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - run: gh release download --repo MorpheApp/MicroG-RE --pattern "*.apk"
      - run: mv *.apk 1microg.apk
      - uses: actions/upload-artifact@main
        with:
          name: microg
          path: 1microg.apk
